(function () {
  "use strict";
  var Portal = window.KeetaPortal || {}, Builder = Portal.MonthlyArchiveBuilder, UiModel = Portal.MonthlyArchiveUiModel;
  if (!Builder || !UiModel) return;
  var state = { tab: "archive_overview", scope: { register: "EXPRESS", city: "Jeddah", platform: "keeta", month: "2026-07" }, run: null };
  var families = Object.keys(Builder.COLLECTIONS);
  function esc(v) { return String(v == null ? "" : v).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
  function collections() { var result = {}, ds = Portal.Runtime && Portal.Runtime.dataStore; Object.keys(Builder.COLLECTIONS).forEach(function (f) { var n = Builder.COLLECTIONS[f]; try { result[n] = ds && ds.getAll ? ds.getAll(n) : []; } catch (_) { result[n] = []; } }); return result; }
  function render() {
    var section = document.getElementById("page-archive-shell"); if (!section) return;
    var all = collections();
    state.run = Builder.buildPreview(all, state.scope, { sourceProfile: new URLSearchParams(location.search).get("storageProfile") || "local", createdAt: "" });
    var view = UiModel.createView(state.run, state.tab), body = renderTab(view);
    section.innerHTML = '<style>.archive-shell{display:grid;gap:14px}.archive-tabs,.archive-scope,.archive-kpis{display:flex;gap:8px;flex-wrap:wrap}.archive-tab{border:1px solid #d8dee8;background:#fff;border-radius:8px;padding:8px 11px;cursor:pointer}.archive-tab.active{background:#173f5f;color:#fff}.archive-scope label{display:grid;gap:4px;min-width:145px}.archive-scope select,.archive-scope input{padding:8px;border:1px solid #ccd5e2;border-radius:7px}.archive-kpi{min-width:130px;padding:12px;border-radius:10px;background:#f6f8fb}.archive-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:8px}.archive-family,.archive-row{border:1px solid #e0e5ec;border-radius:8px;padding:10px;background:#fff}.archive-row button{margin-top:7px}.archive-status{padding:3px 7px;border-radius:999px;background:#fff3cd}.archive-blocked{background:#f8d7da}.archive-drawer{position:fixed;inset:0 0 0 auto;width:min(480px,92vw);z-index:9999;background:#fff;box-shadow:-8px 0 30px #0003;padding:20px;overflow:auto}.archive-drawer[hidden]{display:none}.archive-json{white-space:pre-wrap;word-break:break-word;font-size:12px}</style>' +
      '<div class="archive-shell" data-archive-marker="prompt-8-14" data-read-only="true"><div><span class="eyebrow">Monthly Archive Foundation</span><h2 class="section-title">Read-only monthly snapshot preview</h2><div class="note">Preview only. Nothing is saved, closed, reset, reconciled, or calculated.</div></div>' +
      '<div class="archive-tabs">' + view.tabs.map(function(t){return '<button class="archive-tab '+(t.id===view.activeTab?'active':'')+'" data-archive-tab="'+t.id+'">'+esc(t.label)+'</button>';}).join('') + '</div>' +
      '<div class="archive-scope"><label>Register<input id="archiveRegister" value="'+esc(state.scope.register)+'"></label><label>City<input id="archiveCity" value="'+esc(state.scope.city)+'"></label><label>Platform<input id="archivePlatform" value="'+esc(state.scope.platform)+'"></label><label>Month / cycle<input id="archiveMonth" type="month" value="'+esc(state.scope.month)+'"></label></div>' +
      '<div class="archive-kpis"><div class="archive-kpi"><b>'+view.kpis.items+'</b><br>Snapshot items</div><div class="archive-kpi"><b>'+view.kpis.families+'</b><br>Families</div><div class="archive-kpi"><b>'+view.kpis.warnings+'</b><br>Warnings</div><div class="archive-kpi"><b>'+view.kpis.blockers+'</b><br>Blockers</div><div class="archive-kpi"><b>'+(view.performanceIncluded?'Included':'Missing')+'</b><br>Performance</div><div class="archive-kpi"><b>'+(view.validityIncluded?'Included':'Missing')+'</b><br>Validity</div></div>' + body +
      '<aside id="archiveDetailDrawer" class="archive-drawer" hidden><button data-archive-close>Close</button><h3>Read-only archive detail</h3><pre id="archiveDetailJson" class="archive-json"></pre></aside></div>';
  }
  function renderTab(v) {
    if (v.activeTab === "archive_issues") return '<div class="card"><h3>Archive Issues</h3>'+(v.findings.length?v.findings.map(function(f){return '<div class="archive-row '+(f.level==='blocked'?'archive-blocked':'')+'"><span class="archive-status">'+esc(f.status)+'</span> '+esc(f.message)+'</div>';}).join(''):'<div class="note">No archive blockers or warnings.</div>')+'</div>';
    if (v.activeTab === "archive_source_traceability") return '<div class="card"><h3>Archive Source Traceability</h3>'+(v.sourceBatches.length?v.sourceBatches.map(function(b,i){return row('Batch '+esc(b.batchId||b.id), esc(b.sourceFileName||b.fileName), 'import_batches', i);}).join(''):'<div class="note">No source batches in this scope.</div>')+'</div>';
    if (v.activeTab === "archive_runs") return '<div class="card"><h3>Archive Runs</h3><div class="archive-row"><b>'+esc(state.run.archiveRunId)+'</b><br>Status: '+esc(state.run.status)+' · immutable preview contract<br><span class="muted">Explicit archive creation is intentionally unavailable.</span></div></div>';
    if (v.activeTab === "monthly_archive_preview") return '<div class="card"><h3>Monthly Archive Preview</h3><div class="archive-grid">'+families.map(function(f){var rows=state.run.items[f]||[];return '<div class="archive-family"><b>'+esc(f)+'</b><br>'+rows.length+' items'+(rows.length?'<br><button data-archive-detail="'+f+'" data-index="0">Inspect sample</button>':'')+'</div>';}).join('')+'</div></div>';
    return '<div class="card"><h3>Archive Overview</h3><div class="archive-grid">'+v.counts.filter(function(x){return x.count;}).map(function(x){return '<div class="archive-family"><b>'+esc(x.family)+'</b><br>'+x.count+' preserved rows</div>';}).join('')+'</div></div>';
  }
  function row(title, detail, family, index) { return '<div class="archive-row"><b>'+title+'</b><br>'+detail+'<br><button data-archive-detail="'+family+'" data-index="'+index+'">Open focused batch</button></div>'; }
  document.addEventListener("click", function(e){ var tab=e.target.closest('[data-archive-tab]'), detail=e.target.closest('[data-archive-detail]'), close=e.target.closest('[data-archive-close]'); if(tab){state.tab=tab.dataset.archiveTab;render();} if(detail){var item=(state.run.items[detail.dataset.archiveDetail]||[])[Number(detail.dataset.index)||0]; if(item){document.getElementById('archiveDetailJson').textContent=JSON.stringify(UiModel.detailFor(item),null,2);document.getElementById('archiveDetailDrawer').hidden=false;}} if(close) document.getElementById('archiveDetailDrawer').hidden=true; });
  document.addEventListener("change", function(e){ var map={archiveRegister:'register',archiveCity:'city',archivePlatform:'platform',archiveMonth:'month'}; if(map[e.target.id]){state.scope[map[e.target.id]]=e.target.value;render();} });
  window.addEventListener("keeta:page-changed", function(e){ if(e.detail && e.detail.page==='archive-shell') render(); });
  window.addEventListener("keeta:route-changed", function(e){ if(e.detail && e.detail.page==='archive-shell'){state.tab=e.detail.subPage||state.tab;render();} });
  setTimeout(render, 450);
  Portal.MonthlyArchiveUI = { render: render, getState: function(){return state;}, openTab:function(tab){state.tab=tab;render();} };
})();
