(function(root,factory){if(typeof module==="object"&&module.exports){module.exports=factory();return;}root.KeetaPortal=root.KeetaPortal||{};root.KeetaPortal.MonthlyClosingPreparationModel=factory();})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  var PREPARATION_TYPE="monthly_closing_preparation";
  var STATUSES=["draft","ready","warning","blocked"];
  var VALIDATION_STATUSES=["ready","warning","blocked","missing_data","under_review","scope_mismatch","future_finance_required"];
  var SECTIONS=["scope","archive_snapshot","dashboard_users","assignments","rider_periods","performance_evidence","validity_evidence","vehicle_evidence","import_traceability","issues_and_blockers","future_finance_boundary"];
  var ROUTES={CL1:{code:"CL1",group:"monthly_closing",page:"monthly-closing-shell",subPage:"closing_overview"},CL2:{code:"CL2",group:"monthly_closing",page:"monthly-closing-shell",subPage:"closing_readiness"},CL3:{code:"CL3",group:"monthly_closing",page:"monthly-closing-shell",subPage:"rider_periods"},CL4:{code:"CL4",group:"monthly_closing",page:"monthly-closing-shell",subPage:"evidence_matrix"},CL5:{code:"CL5",group:"monthly_closing",page:"monthly-closing-shell",subPage:"closing_issues"},CL6:{code:"CL6",group:"monthly_closing",page:"monthly-closing-shell",subPage:"future_finance_boundary"}};
  function createPreparationRun(v){v=v||{};var issues=clone(v.issues||[]),blocked=issues.filter(function(x){return x.severity==="blocked";}).length,warnings=issues.filter(function(x){return x.severity==="warning";}).length;return {preparationRunId:text(v.preparationRunId||v.id||"prep::"+[v.register,v.city,v.platform,v.month].map(text).join("::")),preparationType:PREPARATION_TYPE,status:STATUSES.indexOf(v.status)>=0?v.status:(blocked?"blocked":warnings?"warning":"draft"),register:text(v.register),city:text(v.city),platform:text(v.platform),month:text(v.month).slice(0,7),cycleStartDate:text(v.cycleStartDate),cycleEndDate:text(v.cycleEndDate),archiveRunId:text(v.archiveRunId),sourceArchiveStatus:text(v.sourceArchiveStatus),createdAt:text(v.createdAt),createdBy:text(v.createdBy),readinessScore:Math.max(0,Math.min(100,Number(v.readinessScore)||0)),warningCount:Number(v.warningCount==null?warnings:v.warningCount)||0,blockedCount:Number(v.blockedCount==null?blocked:v.blockedCount)||0,issueCount:Number(v.issueCount==null?issues.length:v.issueCount)||0,sourceBatchIds:unique(v.sourceBatchIds||[]),notes:text(v.notes),sections:normalizeSections(v.sections),issues:issues,readOnly:true,immutableSource:true,mutatesArchive:false};}
  function normalizeSections(v){var out={};SECTIONS.forEach(function(k){out[k]=clone(v&&v[k]!=null?v[k]:(k==="scope"||k==="archive_snapshot"||k==="future_finance_boundary"?{}:[]));});return out;}
  function identityOf(v){v=v||{};return {dashboardUserId:text(v.dashboardUserId||v.userId),courierId:text(v.courierId),ownerIqama:text(v.ownerIqama),ownerName:text(v.ownerName),actualRiderIqama:text(v.actualRiderIqama||v.riderIqama),actualRiderName:text(v.actualRiderName||v.riderName),actualRiderSource:["hr","external"].indexOf(text(v.actualRiderSource).toLowerCase())>=0?text(v.actualRiderSource).toLowerCase():"unknown",assignmentId:text(v.assignmentId||v.id),registeredVehicleSerial:text(v.registeredVehicleSerial||v.vehicleSerial),registeredVehiclePlate:text(v.registeredVehiclePlate||v.plateNumber),actualVehicleSerial:text(v.actualVehicleSerial),actualVehiclePlate:text(v.actualVehiclePlate)};}
  function text(v){return String(v==null?"":v).trim();}function clone(v){return JSON.parse(JSON.stringify(v==null?null:v));}function unique(a){var s={};return a.map(text).filter(function(v){if(!v||s[v])return false;s[v]=1;return true;});}
  return {PREPARATION_TYPE:PREPARATION_TYPE,STATUSES:STATUSES,VALIDATION_STATUSES:VALIDATION_STATUSES,SECTIONS:SECTIONS,ROUTES:ROUTES,createPreparationRun:createPreparationRun,identityOf:identityOf};
});
